def cname():
    countries = ['USA',
    'spain',
    'Italy',
    'United Kingdom',
    'France',
    'Germany',
    'Turkey',
    'Russia',
    'Brazil',
    'Iran',
    'China',
    'Canada',
    'Belgium',
    'Peru',
    'Netherlands',
    'India',
    'Switzerland',
    'Ecuador',
    'Saudi Arabia',
    'Portugal',
    'Mexico',
    'Sweden',
    'Ireland',
    'Pakistan',
    'Chile',
    'Singapore',
    'Israel',
    'Belarus',
    'Austria',
    'Qatar',
    'Japan',
    'United Arab Emirates',
    'Poland',
    'Romania',
    'Ukraine',
    'Indonesia',
    'Korea, South',
    'Denmark',
    'Serbia',
    'Philippines',
    'Bangladesh',
    'Norway',
    'Czechia',
    'Dominican Republic',
    'Colombia',
    'Panama',
    'Australia',
    'South Africa',
    'Egypt',
    'Malaysia',
    'Finland',
    'Morocco',
    'Argentina',
    'Kuwait',
    'Algeria',
    'Moldova',
    'Kazakhstan',
    'Luxembourg',
    'Bahrain',
    'Hungary',
    'Thailand',
    'Greece',
    'Oman',
    'Afghanistan',
    'Nigeria',
    'Armenia',
    'Iraq',
    'Ghana','Uzbekistan','Croatia','Cameroon','Azerbaijan','Bosnia and Herzegovina','Iceland','Estonia','Cuba','Bulgaria','Guinea','North Macedonia',
    'New Zealand','Bolivia','Slovenia','Slovakia','Lithuania','Cote d Ivoire','Senegal','Djibouti','Honduras','Tunisia','Latvia','Cyprus','Kosovo',
    'Kyrgyzstan','Albania','Andorra','Niger','Costa Rica','Lebanon','Diamond Princess','Sri Lanka','Guatemala','Congo (Kinshasa)','Somalia','Burkina Faso',
    'Uruguay','Sudan','Georgia','San Marino','Mali','Maldives','Tanzania','Malta','Jamaica','Jordan','El Salvador','Kenya','Taiwan*','Paraguay','West Bank and Gaza',
    'Venezuela','Gabon','Mauritius','Montenegro','Equatorial Guinea','Vietnam','Guinea-Bissau','Rwanda','Congo (Brazzaville)','Sierra Leone','Liberia',
    'Cabo Verde','Burma','Brunei','Madagascar','Ethiopia','Togo','Cambodia','Zambia','Chad','Trinidad and Tobago','Eswatini','Monaco','Benin','Uganda',
    'Haiti','Bahamas','Guyana','Liechtenstein','Barbados','Mozambique','Tajikistan','Central African Republic','Libya','Nepal','South Sudan','Syria',
    'Eritrea','Mongolia','Malawi','Angola','Zimbabwe','Antigua and Barbuda','Timor-Leste','Botswana','Grenada','Laos','Belize','Fiji','Gambia','Saint Lucia',
    'Dominica','Namibia','Saint Vincent and the Grenadines','Sao Tome and Principe','Burundi','Saint Kitts and Nevis','Nicaragua','Holy See','Seychelles',
    'Suriname','Yemen','MS Zaandam','Mauritania','Papua New Guinea','Bhutan','Western Sahara','Comoros']
    
    return countries

def sname():
    states = ['Andhra Pradesh','Andaman and Nicobar Islands','Arunachal Pradesh','Assam','Bihar','Chandigarh','Chhattisgarh','Dadar and Nagar Haveli','Daman and Diu',
             'Delhi','Lakshadweep','Puducherry','Goa','Gujarat','Haryana','Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra',
             'Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal']
    
    return states